name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - name: Test
      run: make test
    - name: Build
      run: make
    - name: Set current date as env variable
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Upload Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v3
      with:
        tag_name: nightly-tag-${{ env.date }}-${{ github.run_number }}
        name: release-${{ env.date }}
        files: bin/*
        draft: false
